---
title: "GraficoTema3"
author: "Iker Cuadros Ruiz, Guillem García Garro, Carles Pascual i Sivera"
date: "2024-02-19"
output:
  pdf_document: default
  html_document: default
subtitle: "Tratamiento de Datos, Grado en Ciencia de Datos - UV"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 0. Comprobación e instalación de paquetes necesarios.

```{r include=FALSE}

# Borramos los datos del historial
rm(list = ls())

# Especificamos las librerías necesarias en esta lista
packages = c("readr", "ggplot2", "dplyr", "shiny", "plotly", "shinydashboard")

# Check si cada package esta en la mquina
# Si no lo están se instalará
package.check <- lapply(packages, FUN = 
  function(x) {
    if (!require(x, character.only = TRUE)) {
      install.packages(x, 
                       dependencies = TRUE,
                       repos = 'http://cran.rediris.es')
      library(x, character.only = TRUE)
    }
  })

# verify they are loaded
search()
```

## 1. Importación de datos.

```{r}

# library(readr)
df.covid <- read_csv("data/owid-covid-data.csv", 
    col_types = cols(date = col_date(format = "%Y-%m-%d")), 
    na = "NA")

df.covid$location <- as.factor(df.covid$location)

```

## 2. Filtrado de Datos

```{r}

# library(dplyr)

# Se cogen los datos de los paises a analizar
countries <- c("Spain", "United States", "United Kingdom", "Japan", "France", "Italy", "Germany", "Canada")
countries <- sort(countries, decreasing = FALSE)

# Definición de la lista de colores en funcion de la longitud de la lista
# Se poner el color rojo en la tercera posición porque es donde se queda
# españa al ordenar los paises en la leyenda
colores <- c()
for ( i in 1:(length(countries)-1) ) {
  colores <- c(colores, sample(colors(1), 1))
}

# Buscar la posición en la que se encuentra españa, para asignarle 
# el color rojo en la lista de valores
posEsp <- match("Spain", countries)

colores <- c(colores[1:posEsp-1], "red", colores[posEsp:length(colores)])

# Filtrado de datos por paises requeridos y fecha inicial
df.covid.filtered <- df.covid %>%
  subset(location %in% countries
         & new_deaths > 0
         & date >= as.Date("2020-02-13"))

df.covid.filt.spain <- df.covid.filtered %>%
  subset(location == "Spain")

```

## 3. Creación del Gráfico

```{r}

# library(ggplot2)

# Creación del grafico
grafico <- ggplot(df.covid.filtered, aes(x = date, y = new_deaths_smoothed_per_million)) +
  geom_line( aes(col= location), linewidth = 0.5, alpha = 0.65) +
  geom_line(data = df.covid.filt.spain, linewidth = 1, col = "red") +
  scale_color_manual(values = colores) + 
  scale_x_date(date_labels = ("%b %d,%Y"), breaks = "9 month") +
  scale_y_continuous(limits = c(0,21), breaks = seq(0, 18, by = 2))

# Adición de las etiquetas necesatias
grafico <- grafico +
  labs(title = "Grupo N: Daily new confirmed COVID-19 deaths per million people",
       subtitle = "7-day rolling average.\nFor some countries the number of confirmed deaths is much lower than the true number of deaths.\nThis is because of limited testing and challenges in the attribution of the cause of death",
       x = "",
       y = "",
       col = "País",
       alt = "Deaths evolution graphic",
       caption = "Source: Johns Hopkins University CSSE COVID-19 Data") + 
  theme_minimal()

# Cambio del tipo de letra de las etiquetas
grafico <- grafico + 
  theme(text = element_text(family = "sans"),
        plot.title = element_text(size = 14, face = "bold"),
        # plot.subtitle = element_text(size = 12),
        plot.caption =  element_text(size = 8, face = "italic", hjust = -.2))
grafico

ggplotly(grafico)

ggsave(filename = "./figures/prueba.pdf", plot = grafico, width = 8, height = 6)

```

```{r}

# library(shiny)
# library(ggplot2)
# library(plotly)
# library(shinydashboard)

# Definición de la UI
ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody()
)

# Definición del server
server <- function(input, output) {
  
}

# Llamamos a la aplicación
shinyApp(ui = ui, server = server)

```
